### ISSUE TITLE
BUG: Instance scheduler fails when action is not supported

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform-instance-scheduler#138]
## Expected behaviour

Large numbers of skipped instances belonging to an Autoscaling group should not trigger a message indicating that the number of skipped instances is too low.

## Actual behaviour

```
main_int_test.go:46: 
  Error Trace:	/home/runner/work/modernisation-platform-instance-scheduler/modernisation-platform-instance-scheduler/instance-scheduler/main_int_test.go:46
  Error:      	"20" is not greater than "20"
  Test:       	TestHandler/Test_request
  Messages:   	Number of skipped instances that belong to an Auto Scaling group seems too low. Please manually check the Instance Scheduler logs and verify this is reasonable. If it is reasonable, modify and adjust this test accordingly.
```

## Steps to reproduce

See this github action for an example of the error ocurring: https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/actions/runs/3984953166/jobs/6831747201

**Comment by connormaglynn** [comment]
## 🆙 Update

- 🔧 Thresholds amended in https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/pull/908 to reduce the chances of this happening again
- 🙈 This is more of a current "feature" than a bug 🐛 as we're currently depending on checks against the live environment using some static values to validate that code changes don't break anything. Discussed in a bit more detail in this [thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1712051311040569) 🧵 
- 💅 In the long term, we want to move away from depending on the live state to validate code changes and shift our checks left by refactoring the code to make it more modular and easier to read, adding additional unit testing (currently only 68% of the functionality is covered by unit tests), integration tests with mocked environments instead of live ones etc.

## 👀 Remaining Work

- Going to create a ticket to start addressing some of the technical debt issues, starting with getting unit test coverage up (which will hopefully encourage some refactors of the current code 🤞) - I won't create any more tickets than this for now, and we can decide to invest more time into this code if we feel it's worth the effort ✅
